### ISSUE TITLE
Audio not playing

### ISSUE THREAD

**Issue by TheCyberCoder1** [TheCyberCoder1/Unity_Spinny_Rocket#4]
during the crash the audio is not played, along with the success audio for hitting the finish.

**Comment by arbusam** [comment]
I will will try to fix this after you merge the lighting bug (#2) . Otherwise there will be a lot of conflicts.

**Comment by arbusam** [comment]
Remove the invalid tag. That means that the issue is invalid.

**Comment by TheCyberCoder1** [comment]
I have resolved this issue with my latest push

I added`Invoke("LoadLevel", levelLoadDelay);` which has delayed the load and let the audio to play
